### ISSUE TITLE
Can't get any speed up!

### ISSUE THREAD

**Issue by felixsanz** [ethansmith2000/ImprovedTokenMerge#1]
Hi there!

Recently I've write a big article about SDXL optimizations:

**Ultimate guide to optimizing Stable Diffusion XL**
https://www.felixsanz.dev/articles/ultimate-guide-to-optimizing-stable-diffusion-xl

I wanted to include your method, but I can't get any speed up (in fact, time increases 0.1s). Can you help me debug what I'm doing wrong? Also `tomesd` doesn't give any speed up either.

In the case of `todo`, this is (more or less) the code I'm using:

```py
from time import perf_counter
import torch
from diffusers import AutoPipelineForText2Image
from utils import patch_attention_proc, remove_patch

pipe = AutoPipelineForText2Image.from_pretrained(
  'stabilityai/stable-diffusion-xl-base-1.0',
  use_safetensors=True,
  torch_dtype=torch.float16,
  variant='fp16',
).to('cuda')

downsample_factor = 4
ratio = 0.75
merge_method = "downsample"
merge_tokens = "keys/values"
downsample_method = "nearest-exact"
timestep_threshold_switch = 0.3
timestep_threshold_stop = 0.0
secondary_merge_method = "similarity"
extra_guidance_scale = 1.5

token_merge_args = {
  "ratio": ratio, # ratio of how much tokens to merge for similarity method, will be used if you specify similarity for method or once the method switches
  "merge_tokens": merge_tokens, # ["keys/values","all"] # which tokens to merge, either keys/values or all
  "merge_method": merge_method, # ["none","similarity", "downsample"] # which method to use for merging tokens
  "downsample_method": downsample_method, # specify any of the interpolation methods used for F.interpolate. spoiler, this one works the best and is the fastest
  "downsample_factor": downsample_factor, # factor to downsample tokens by, seems best to use an integer
  "timestep_threshold_switch": timestep_threshold_switch, # if using downsample, what % left of generation to switch to secondary method, 0.3 means once 30% of generation is left, switch to similarity method
  "timestep_threshold_stop": timestep_threshold_stop, # what % left in the run to revert to normal attention, 0.0 means never revert
  "secondary_merge_method": secondary_merge_method, # ["none","similarity", "downsample"] # which method to use for merging tokens once the threshold is reached
  "downsample_factor_level_2": 1, # downsample amount to use for down block 2 depth, 1 is typically fine here as the largest resolution blocks are most expensive, but can try 2 for very large resolutions
  "ratio_level_2": 0.0, # ratio for similarity based merging for down block 2 depth, 0.0 means never use similarity based merging
}

patch_attention_proc(pipe.unet, token_merge_args=token_merge_args)

generator = torch.Generator(device='cuda')
generator.manual_seed(0)

image_start = perf_counter()

image = pipe(
  prompt='3/4 shot, candid photograph of a beautiful 30 year old redhead woman with messy dark hair, peacefully sleeping in her bed, night, dark, light from window, dark shadows, masterpiece, uhd, moody',
  generator=generator,
).images[0]

image.save(f'image.png')

print(perf_counter() - image_start)
```

Any idea why I can't get any speed up? On your HF demo I'm getting it. The demo works fine apparently.

Thanks!

**Comment by ethansmith2000** [comment]
I should make this more clear on the readme, SDXL models do not run attention at the top block, therefore, if you want to perform downsampling you have to use depth_2 to specify the downsample rate. 

However, with SDXL in general you really wont see as much potential for speedup, since they smartly built the network more efficiently to begin with, and much of the time spent during inference comes from the network having many more layers, deeper network.

If you try rendering at 2048x2048 and set downsample_depth_2 to 2, you may see some speedups

Great article btw! very thorough

**Comment by felixsanz** [comment]
> I should make this more clear on the readme, SDXL models do not run attention at the top block, therefore, if you want to perform downsampling you have to use depth_2 to specify the downsample rate.
> 
> However, with SDXL in general you really wont see as much potential for speedup, since they smartly built the network more efficiently to begin with, and much of the time spent during inference comes from the network having many more layers, deeper network.
> 
> If you try rendering at 2048x2048 and set downsample_depth_2 to 2, you may see some speedups
> 
> Great article btw! very thorough

Something inside me was telling me that this was not for SDXL, but since your method was so modern I thought you had implemented it in the latest version of SD.

No problem then! I still use 1.5 for most things, but unfortunately the article is about SDXL so I can't include your method :(

Good job whatsoever! Thanks for replying

**Comment by ethansmith2000** [comment]
Worth giving it a try at 2048x2048 or so using deepshrink or img2img in tandem! I personally have not tried but a user commented on a reddit post that they got good results with it using the comfyui implementation https://github.com/ethansmith2000/comfy-todo

**Comment by felixsanz** [comment]
I'll explore it, but I don't like using high resolutions on SD because it introduces artifacts (like another head coming out of the arm XD), it's better to just use upscalers if need higher resolution. But if speed up is decent I'll add it to the article anyway
